"""Offline resolution of a wine from whatever the user has typed.

The point of this module is that autofill should never come back empty-handed.
Most of the add-bottle form follows from the *appellation*, not the producer, so
there are three ways in and they compound:

    producer      -> its appellation -> country, region, grapes, type, window
    appellation   -> country, region, grapes, type, window
    region/country-> country, and the grapes typical of the region

A producer nobody has heard of, typed alongside "Napa Valley", still yields a
country, a plausible grape set, and a drinking window. That beats a blank form,
and it is deterministic and free — no model call.

The dataset is data/wine_reference.json, generated by scripts/build_reference.py.
`web/js/reference.js` implements the same matching against the same file, so the
published site behaves identically with no backend.
"""
from __future__ import annotations

import json
import re
import unicodedata
from functools import lru_cache
from pathlib import Path
from typing import Any, Optional

REFERENCE_PATH = Path(__file__).resolve().parent.parent / "data" / "wine_reference.json"

_PUNCT = re.compile(r"[^\w\s]", re.UNICODE)
_WS = re.compile(r"\s+")

# Match quality, high to low. Anything below `weak` is not a match.
EXACT, STRONG, PARTIAL, WEAK = "exact", "strong", "partial", "weak"


def normalize(text: Optional[str]) -> str:
    if not text:
        return ""
    folded = unicodedata.normalize("NFKD", text)
    folded = "".join(ch for ch in folded if not unicodedata.combining(ch))
    return _WS.sub(" ", _PUNCT.sub(" ", folded)).strip().lower()


@lru_cache(maxsize=1)
def reference() -> dict:
    """The reference dataset. Missing file degrades to empty, not a crash —
    autofill then falls back to the model alone."""
    try:
        return json.loads(REFERENCE_PATH.read_text())
    except (OSError, ValueError):
        return {"appellations": {}, "aliases": {}, "regions": {}, "countries": {},
                "producers": {}, "noise_words": []}


@lru_cache(maxsize=1)
def _noise() -> frozenset[str]:
    return frozenset(reference().get("noise_words", []))


def tokens(text: Optional[str]) -> tuple[str, ...]:
    """Significant words only — "Chateau", "Vineyards", "Estate" and friends
    carry no identifying weight and would match half the table."""
    return tuple(t for t in normalize(text).split() if t and t not in _noise())


def _score(query: str, candidate_key: str) -> Optional[str]:
    """How well a query matches one table key."""
    if not query or not candidate_key:
        return None
    if query == candidate_key:
        return EXACT

    query_order = tokens(query)
    query_tokens, candidate_tokens = set(query_order), set(tokens(candidate_key))
    if not query_tokens or not candidate_tokens:
        return None
    if query_tokens == candidate_tokens:
        return EXACT
    # "Caymus" finds "Caymus Vineyards" — the user typed part of a longer name.
    if query_tokens <= candidate_tokens:
        return STRONG
    # The other direction is not the same thing. Here the user typed words the
    # candidate does not have, and those words belong to *something*. When they
    # trail the name they are qualifiers and the match holds ("Chateau Margaux
    # 1er" is still Chateau Margaux); when they lead it, the name being typed is
    # a different one ("Sonoma Ridge Cellars" is not Ridge Vineyards). A winery
    # is named front-first, so the query's first significant word has to be part
    # of the match.
    if candidate_tokens <= query_tokens:
        return STRONG if query_order[0] in candidate_tokens else PARTIAL

    overlap = query_tokens & candidate_tokens
    if not overlap:
        return None
    ratio = len(overlap) / max(len(query_tokens), len(candidate_tokens))
    if ratio >= 0.6:
        return PARTIAL
    # A single shared word is only meaningful when it is a substantial one.
    if len(overlap) == 1 and max(len(w) for w in overlap) >= 6:
        return WEAK
    return None


_RANK = {EXACT: 0, STRONG: 1, PARTIAL: 2, WEAK: 3}


_DEMOTE = {EXACT: STRONG, STRONG: PARTIAL, PARTIAL: WEAK, WEAK: None}


def _identity(entry: dict) -> str:
    """What an entry claims about a wine's origin. Two producers that resolve to
    the same appellation are interchangeable for our purposes; two that do not
    are a genuine ambiguity."""
    return entry.get("appellation") or entry.get("name") or ""


def _best(query: Optional[str], table: dict) -> tuple[Optional[dict], Optional[str]]:
    """Best entry in a table for a query, with its match quality.

    Where several entries tie at the best quality, the tie is only harmless if
    they agree on where the wine is from. "Mondavi" hits both `Robert Mondavi
    Winery` and `Mondavi Reserve`, and both say Napa Valley — either answer is
    the same answer. "Smith" hits six producers spread over Washington,
    Bordeaux, Napa and Sonoma, and picking whichever one the dict happened to
    yield first would state a place we cannot back. That is demoted a level, so
    the caller stops treating it as authoritative."""
    key = normalize(query)
    if not key or not table:
        return None, None
    if key in table:
        return table[key], EXACT

    best_quality: Optional[str] = None
    tied: list[dict] = []
    for candidate_key, entry in table.items():
        quality = _score(key, candidate_key)
        if quality is None:
            continue
        if best_quality is None or _RANK[quality] < _RANK[best_quality]:
            best_quality, tied = quality, [entry]
        elif quality == best_quality:
            tied.append(entry)

    if best_quality is None:
        return None, None
    if len({_identity(e) for e in tied}) > 1:
        best_quality = _DEMOTE[best_quality]
        if best_quality is None:
            return None, None
    return tied[0], best_quality


@lru_cache(maxsize=1)
def _grape_words() -> tuple[tuple[str, str], ...]:
    """(normalized, display) grape names, longest first so "Grenache Blanc"
    is matched before "Grenache"."""
    words = [(normalize(g), g) for g in reference().get("grape_words", [])]
    return tuple(sorted((w for w in words if w[0]), key=lambda w: -len(w[0])))


def grapes_in(text: Optional[str]) -> list[str]:
    """Grapes named in a string, in the order they appear.

    This is reading the label, not guessing: "Silencieux Cabernet Sauvignon"
    says what it is, and so does a wine from a producer the reference has never
    heard of. Matching is on whole words against a normalized copy, and a
    matched grape is blanked out so "Grenache Blanc" cannot also report
    "Grenache".
    """
    haystack = f" {normalize(text)} "
    if haystack.strip() == "":
        return []
    found: list[tuple[int, str]] = []
    for key, display in _grape_words():
        position = haystack.find(f" {key} ")
        if position == -1:
            continue
        found.append((position, display))
        haystack = haystack.replace(f" {key} ", " " + "\u0000" * len(key) + " ")
    return [display for _, display in sorted(found)]


@lru_cache(maxsize=1)
def _white_grapes() -> frozenset[str]:
    return frozenset(normalize(g) for g in reference().get("white_grapes", []))


# Places whose colour is a fact about the place, not about the grape: Champagne
# is Chardonnay and is not a white wine; nor is Sauternes or Madeira.
_COLOUR_FROM_GRAPE = {"red", "white", "rose"}


def colour_of(grapes: list[str]) -> Optional[str]:
    """"white" or "red" when every named grape agrees, else None."""
    if not grapes:
        return None
    whites = _white_grapes()
    keys = [normalize(g) for g in grapes]
    if not whites or any(not k for k in keys):
        return None
    if all(k in whites for k in keys):
        return "white"
    if all(k not in whites for k in keys):
        return "red"
    return None


def find_bottling(producer_entry: Optional[dict], wine_name: Optional[str]) -> Optional[dict]:
    """The producer's own wine that the typed cuvée names, if any."""
    if not producer_entry or not wine_name:
        return None
    bottlings = producer_entry.get("bottlings") or []
    if not bottlings:
        return None
    table = {normalize(b["wine_name"]): b for b in bottlings if b.get("wine_name")}
    entry, _ = _best(wine_name, table)
    return entry


def find_producer(name: Optional[str]) -> tuple[Optional[dict], Optional[str]]:
    return _best(name, reference().get("producers", {}))


def find_appellation(name: Optional[str]) -> tuple[Optional[dict], Optional[str]]:
    """Appellations, following aliases first ("Los Carneros" -> "Carneros")."""
    data = reference()
    key = normalize(name)
    if not key:
        return None, None
    canonical = data.get("aliases", {}).get(key, key)
    appellations = data.get("appellations", {})
    if canonical in appellations:
        return appellations[canonical], EXACT
    return _best(name, appellations)


def find_region(name: Optional[str]) -> tuple[Optional[dict], Optional[str]]:
    return _best(name, reference().get("regions", {}))


def find_country(name: Optional[str]) -> tuple[Optional[dict], Optional[str]]:
    return _best(name, reference().get("countries", {}))


def _region_of(place: dict, kind: Optional[str]) -> str:
    """The region a place sits in, whichever kind of place it is."""
    return place["region"] if kind == "appellation" else place["name"]


def resolve(
    *,
    producer: Optional[str] = None,
    vintage: Optional[int] = None,
    wine_name: Optional[str] = None,
    appellation: Optional[str] = None,
    region: Optional[str] = None,
    country: Optional[str] = None,
) -> dict:
    """Resolve everything the reference can, from whatever was supplied.

    Returns:
        {
          "wine":     partial wine fields (only what is actually known),
          "sources":  {field: "reference"} for provenance,
          "producer_match": exact|strong|partial|weak|None,
          "place":    the appellation/region entry that drove it, if any,
          "typical":  fields that are the *place's* norm rather than this
                      wine's fact — the model may override these.
          "bottlings": the producer's known wines, so the form can offer them.
          "bottling": the one the typed cuvée matched, if any.
        }

    Naming a cuvée narrows the answer. An appellation can only say what is
    typical of the place: Willow Creek District says Grenache, Syrah and
    Mourvedre, which is right for Denner's Ditch Digger, wrong for its Theresa
    and wrong for its Mother of Exiles. A matched bottling states its own
    grapes, and a cuvée whose name contains a grape states it too.
    """
    wine: dict[str, Any] = {}
    typical: set[str] = set()

    producer_entry, producer_match = find_producer(producer)

    # Where the user says the wine is from.
    # People do not respect field boundaries — "Napa Valley" gets typed into
    # the region box as often as the appellation one — so every place-ish field
    # is tried against the appellation table before falling back to regions.
    user_place, user_kind = None, None
    for candidate in (appellation, region):
        entry, _ = find_appellation(candidate)
        if entry:
            user_place, user_kind = entry, "appellation"
            break
    if user_place is None:
        for candidate in (region, appellation):
            entry, _ = find_region(candidate)
            if entry:
                user_place, user_kind = entry, "region"
                break

    # Where the producer says it is from. Only a confident producer match gets
    # to speak: an uncertain one naming an appellation is how a cellar record
    # acquires a plausible lie.
    producer_place = None
    if producer_entry and producer_match in (EXACT, STRONG):
        producer_place, _ = find_appellation(producer_entry["appellation"])

    if user_place is None:
        place, place_kind = producer_place, ("appellation" if producer_place else None)
    elif producer_place and _region_of(producer_place, "appellation") == _region_of(user_place, user_kind):
        # They agree on the region and the producer knows the sub-appellation:
        # "Venge Vineyards" plus a typed "Napa" is Calistoga, not Napa Valley.
        place, place_kind = producer_place, "appellation"
    else:
        # They disagree. The user is holding the bottle; the producer table is
        # a guess about a name. Trust the user, and do not quietly relocate the
        # wine to wherever the producer index happened to point.
        place, place_kind = user_place, user_kind

    if producer_entry and producer_match in (EXACT, STRONG):
        wine["producer"] = producer_entry["name"]

    if place:
        wine["country"] = place["country"]
        wine["region"] = place["region"] if place_kind == "appellation" else place["name"]
        if place_kind == "appellation":
            wine["appellation"] = place["name"]
        # Grapes, style and ageing are what the place typically gives. A specific
        # cuvée can differ, so they are marked for the model to override.
        wine["varietals"] = list(place["grapes"])
        wine["wine_type"] = place["type"]
        typical |= {"varietals", "wine_type", "drink_from", "drink_to"}
        if vintage:
            wine["drink_from"] = vintage + place["age"][0]
            wine["drink_to"] = vintage + place["age"][1]
    else:
        # No place at all: a bare country is still worth filling.
        entry, _ = find_country(country)
        if entry:
            wine["country"] = entry["name"]

    # Naming the wine beats naming the place. A matched bottling knows its own
    # grapes; failing that, a cuvée whose name contains a grape has told us.
    # Either way these stop being "typical" — they are about this bottle.
    bottling = find_bottling(producer_entry, wine_name) if producer_entry else None
    stated = list(bottling.get("varietals") or []) if bottling else []
    if not stated:
        stated = grapes_in(wine_name)
    if stated:
        wine["varietals"] = stated
        typical.discard("varietals")
    if bottling and bottling.get("wine_type"):
        wine["wine_type"] = bottling["wine_type"]
        typical.discard("wine_type")
    elif stated and wine.get("wine_type") in _COLOUR_FROM_GRAPE:
        colour = colour_of(stated)
        if colour and colour != wine["wine_type"]:
            wine["wine_type"] = colour
            typical.discard("wine_type")

    return {
        "wine": wine,
        "sources": {key: "reference" for key in wine},
        "producer_match": producer_match if producer_entry else None,
        "producer_name": producer_entry["name"] if producer_entry else None,
        "place": {"kind": place_kind, "name": place["name"]} if place else None,
        "typical": sorted(typical),
        # Offered to the user as "which one?", and echoed back as a cuvée.
        "bottlings": list((producer_entry or {}).get("bottlings") or [])
        if producer_match in (EXACT, STRONG) else [],
        "bottling": bottling["wine_name"] if bottling else None,
    }


def stats() -> dict:
    data = reference()
    return {
        "producers": len(data.get("producers", {})),
        "appellations": len(data.get("appellations", {})),
        "regions": len(data.get("regions", {})),
        "countries": len(data.get("countries", {})),
    }
