"""Offline resolution of a wine from whatever the user has typed.

The point of this module is that autofill should never come back empty-handed.
Most of the add-bottle form follows from the *appellation*, not the producer, so
there are three ways in and they compound:

    producer      -> its appellation -> country, region, grapes, type, window
    appellation   -> country, region, grapes, type, window
    region/country-> country, and the grapes typical of the region

A producer nobody has heard of, typed alongside "Napa Valley", still yields a
country, a plausible grape set, and a drinking window. That beats a blank form,
and it is deterministic and free — no model call.

The dataset is data/wine_reference.json, generated by scripts/build_reference.py.
`web/js/reference.js` implements the same matching against the same file, so the
published site behaves identically with no backend.
"""
from __future__ import annotations

import json
import re
import unicodedata
from functools import lru_cache
from pathlib import Path
from typing import Any, Optional

REFERENCE_PATH = Path(__file__).resolve().parent.parent / "data" / "wine_reference.json"

_PUNCT = re.compile(r"[^\w\s]", re.UNICODE)
_WS = re.compile(r"\s+")

# Match quality, high to low. Anything below `weak` is not a match.
EXACT, STRONG, PARTIAL, WEAK = "exact", "strong", "partial", "weak"


def normalize(text: Optional[str]) -> str:
    if not text:
        return ""
    folded = unicodedata.normalize("NFKD", text)
    folded = "".join(ch for ch in folded if not unicodedata.combining(ch))
    return _WS.sub(" ", _PUNCT.sub(" ", folded)).strip().lower()


@lru_cache(maxsize=1)
def reference() -> dict:
    """The reference dataset. Missing file degrades to empty, not a crash —
    autofill then falls back to the model alone."""
    try:
        return json.loads(REFERENCE_PATH.read_text())
    except (OSError, ValueError):
        return {"appellations": {}, "aliases": {}, "regions": {}, "countries": {},
                "producers": {}, "noise_words": []}


@lru_cache(maxsize=1)
def _noise() -> frozenset[str]:
    return frozenset(reference().get("noise_words", []))


def tokens(text: Optional[str]) -> tuple[str, ...]:
    """Significant words only — "Chateau", "Vineyards", "Estate" and friends
    carry no identifying weight and would match half the table."""
    return tuple(t for t in normalize(text).split() if t and t not in _noise())


def _score(query: str, candidate_key: str) -> Optional[str]:
    """How well a query matches one table key."""
    if not query or not candidate_key:
        return None
    if query == candidate_key:
        return EXACT

    query_tokens, candidate_tokens = set(tokens(query)), set(tokens(candidate_key))
    if not query_tokens or not candidate_tokens:
        return None
    if query_tokens == candidate_tokens:
        return EXACT
    # "Caymus" finds "Caymus Vineyards"; "Chateau Margaux 1er" finds "Chateau Margaux".
    if query_tokens <= candidate_tokens or candidate_tokens <= query_tokens:
        return STRONG

    overlap = query_tokens & candidate_tokens
    if not overlap:
        return None
    ratio = len(overlap) / max(len(query_tokens), len(candidate_tokens))
    if ratio >= 0.6:
        return PARTIAL
    # A single shared word is only meaningful when it is a substantial one.
    if len(overlap) == 1 and max(len(w) for w in overlap) >= 6:
        return WEAK
    return None


_RANK = {EXACT: 0, STRONG: 1, PARTIAL: 2, WEAK: 3}


def _best(query: Optional[str], table: dict) -> tuple[Optional[dict], Optional[str]]:
    """Best entry in a table for a query, with its match quality."""
    key = normalize(query)
    if not key or not table:
        return None, None
    if key in table:
        return table[key], EXACT

    best_entry, best_quality = None, None
    for candidate_key, entry in table.items():
        quality = _score(key, candidate_key)
        if quality is None:
            continue
        if best_quality is None or _RANK[quality] < _RANK[best_quality]:
            best_entry, best_quality = entry, quality
            if quality == EXACT:
                break
    return best_entry, best_quality


def find_producer(name: Optional[str]) -> tuple[Optional[dict], Optional[str]]:
    return _best(name, reference().get("producers", {}))


def find_appellation(name: Optional[str]) -> tuple[Optional[dict], Optional[str]]:
    """Appellations, following aliases first ("Los Carneros" -> "Carneros")."""
    data = reference()
    key = normalize(name)
    if not key:
        return None, None
    canonical = data.get("aliases", {}).get(key, key)
    appellations = data.get("appellations", {})
    if canonical in appellations:
        return appellations[canonical], EXACT
    return _best(name, appellations)


def find_region(name: Optional[str]) -> tuple[Optional[dict], Optional[str]]:
    return _best(name, reference().get("regions", {}))


def find_country(name: Optional[str]) -> tuple[Optional[dict], Optional[str]]:
    return _best(name, reference().get("countries", {}))


def resolve(
    *,
    producer: Optional[str] = None,
    vintage: Optional[int] = None,
    appellation: Optional[str] = None,
    region: Optional[str] = None,
    country: Optional[str] = None,
) -> dict:
    """Resolve everything the reference can, from whatever was supplied.

    Returns:
        {
          "wine":     partial wine fields (only what is actually known),
          "sources":  {field: "reference"} for provenance,
          "producer_match": exact|strong|partial|weak|None,
          "place":    the appellation/region entry that drove it, if any,
          "typical":  fields that are the *place's* norm rather than this
                      wine's fact — the model may override these.
        }
    """
    wine: dict[str, Any] = {}
    typical: set[str] = set()

    producer_entry, producer_match = find_producer(producer)

    # An appellation the user typed is stronger evidence than one inferred from
    # a producer name that only partly matched.
    # People do not respect field boundaries — "Napa Valley" gets typed into
    # the region box as often as the appellation one — so every place-ish field
    # is tried against the appellation table before falling back to regions.
    place, place_kind = None, None
    for candidate in (appellation, region):
        entry, _ = find_appellation(candidate)
        if entry:
            place, place_kind = entry, "appellation"
            break
    if place is None and producer_entry and producer_match in (EXACT, STRONG):
        entry, _ = find_appellation(producer_entry["appellation"])
        if entry:
            place, place_kind = entry, "appellation"
    if place is None:
        for candidate in (region, appellation):
            entry, _ = find_region(candidate)
            if entry:
                place, place_kind = entry, "region"
                break
    if place is None and producer_entry:
        entry, _ = find_appellation(producer_entry["appellation"])
        if entry:
            place, place_kind = entry, "appellation"

    if producer_entry and producer_match in (EXACT, STRONG):
        wine["producer"] = producer_entry["name"]

    if place:
        wine["country"] = place["country"]
        wine["region"] = place["region"] if place_kind == "appellation" else place["name"]
        if place_kind == "appellation":
            wine["appellation"] = place["name"]
        # Grapes, style and ageing are what the place typically gives. A specific
        # cuvée can differ, so they are marked for the model to override.
        wine["varietals"] = list(place["grapes"])
        wine["wine_type"] = place["type"]
        typical |= {"varietals", "wine_type", "drink_from", "drink_to"}
        if vintage:
            wine["drink_from"] = vintage + place["age"][0]
            wine["drink_to"] = vintage + place["age"][1]
    else:
        # No place at all: a bare country is still worth filling.
        entry, _ = find_country(country)
        if entry:
            wine["country"] = entry["name"]

    return {
        "wine": wine,
        "sources": {key: "reference" for key in wine},
        "producer_match": producer_match if producer_entry else None,
        "producer_name": producer_entry["name"] if producer_entry else None,
        "place": {"kind": place_kind, "name": place["name"]} if place else None,
        "typical": sorted(typical),
    }


def stats() -> dict:
    data = reference()
    return {
        "producers": len(data.get("producers", {})),
        "appellations": len(data.get("appellations", {})),
        "regions": len(data.get("regions", {})),
        "countries": len(data.get("countries", {})),
    }
