"""California appellations and producers for the autofill reference.

Split out of build_reference.py because California is most of the dataset by
volume — US cellars are mostly Californian, and so is the catalogue of the
flash-sale merchants (Last Bottle and its kind) people actually buy from.

Two tables, consumed by scripts/build_reference.py:

    CALIFORNIA_AVAS       (name, region, country, type, grapes, age)
    CALIFORNIA_PRODUCERS  (producer, appellation)

`age` is (years after vintage it opens, years after it fades). `grapes` are the
dominant plantings, most-planted first. Both are the *appellation's* norm — a
specific cuvée can differ, which is why the resolver marks them "typical" and
lets a model answer override them.

Producers are placed in the AVA they are most identified with. Many work across
several; the point is to resolve a plausible place, not to assert exclusivity.
"""
from __future__ import annotations

# fmt: off
CALIFORNIA_AVAS: list[tuple] = [
    # ---- Napa sub-AVAs ----
    ("Coombsville", "Napa", "United States", "red", ["Cabernet Sauvignon", "Merlot"], (5, 24)),
    ("Atlas Peak", "Napa", "United States", "red", ["Cabernet Sauvignon"], (6, 28)),
    ("Chiles Valley", "Napa", "United States", "red", ["Zinfandel", "Cabernet Sauvignon"], (4, 20)),
    ("Oak Knoll District", "Napa", "United States", "red", ["Cabernet Sauvignon", "Chardonnay"], (4, 20)),
    ("Wild Horse Valley", "Napa", "United States", "red", ["Pinot Noir", "Chardonnay"], (3, 15)),
    # Not a federal AVA, but the name these wines are labelled and sold under.
    ("Pritchard Hill", "Napa", "United States", "red", ["Cabernet Sauvignon"], (6, 28)),
    # ---- Sonoma sub-AVAs ----
    ("Sonoma Valley", "Sonoma", "United States", "red", ["Cabernet Sauvignon", "Zinfandel"], (4, 20)),
    ("Sonoma Mountain", "Sonoma", "United States", "red", ["Cabernet Sauvignon"], (5, 24)),
    ("Moon Mountain District", "Sonoma", "United States", "red", ["Cabernet Sauvignon"], (5, 24)),
    ("Bennett Valley", "Sonoma", "United States", "red", ["Merlot", "Syrah"], (3, 16)),
    ("Green Valley of Russian River Valley", "Sonoma", "United States", "red", ["Pinot Noir", "Chardonnay"], (3, 16)),
    ("Fort Ross-Seaview", "Sonoma", "United States", "red", ["Pinot Noir", "Chardonnay"], (4, 18)),
    ("Petaluma Gap", "Sonoma", "United States", "red", ["Pinot Noir", "Syrah"], (3, 15)),
    ("Rockpile", "Sonoma", "United States", "red", ["Zinfandel", "Cabernet Sauvignon"], (4, 18)),
    ("Fountaingrove District", "Sonoma", "United States", "red", ["Cabernet Sauvignon"], (4, 20)),
    ("Pine Mountain-Cloverdale Peak", "Sonoma", "United States", "red", ["Cabernet Sauvignon"], (5, 22)),
    # ---- Mendocino & Lake ----
    ("Mendocino Ridge", "Mendocino", "United States", "red", ["Zinfandel", "Pinot Noir"], (3, 16)),
    ("Yorkville Highlands", "Mendocino", "United States", "red", ["Pinot Noir", "Sauvignon Blanc"], (3, 15)),
    ("Redwood Valley", "Mendocino", "United States", "red", ["Zinfandel", "Cabernet Sauvignon"], (3, 15)),
    ("Potter Valley", "Mendocino", "United States", "white", ["Riesling", "Sauvignon Blanc"], (2, 10)),
    ("McDowell Valley", "Mendocino", "United States", "red", ["Syrah", "Grenache"], (3, 14)),
    ("Red Hills Lake County", "Lake County", "United States", "red", ["Cabernet Sauvignon"], (4, 18)),
    ("Lake County", "Lake County", "United States", "red", ["Cabernet Sauvignon", "Sauvignon Blanc"], (3, 14)),
    ("Guenoc Valley", "Lake County", "United States", "red", ["Cabernet Sauvignon"], (4, 18)),
    # ---- Monterey, San Benito, Bay Area ----
    ("Monterey", "Central Coast", "United States", "white", ["Chardonnay", "Pinot Noir"], (2, 12)),
    ("Arroyo Seco", "Central Coast", "United States", "white", ["Chardonnay", "Riesling"], (2, 12)),
    ("Chalone", "Central Coast", "United States", "white", ["Chardonnay", "Pinot Noir"], (3, 18)),
    ("Carmel Valley", "Central Coast", "United States", "red", ["Cabernet Sauvignon"], (4, 20)),
    ("Mount Harlan", "Central Coast", "United States", "red", ["Pinot Noir", "Chardonnay"], (4, 20)),
    ("Cienega Valley", "Central Coast", "United States", "red", ["Pinot Noir", "Zinfandel"], (3, 16)),
    ("San Benito", "Central Coast", "United States", "red", ["Pinot Noir", "Cabernet Pfeffer"], (3, 15)),
    ("Santa Clara Valley", "Central Coast", "United States", "red", ["Cabernet Sauvignon", "Zinfandel"], (3, 15)),
    ("Livermore Valley", "Central Coast", "United States", "red", ["Cabernet Sauvignon", "Petite Sirah"], (3, 16)),
    ("Contra Costa County", "Central Coast", "United States", "red", ["Zinfandel", "Mourvedre"], (3, 15)),
    # ---- Santa Barbara & San Luis Obispo ----
    ("Santa Maria Valley", "Central Coast", "United States", "red", ["Pinot Noir", "Chardonnay"], (3, 16)),
    ("Ballard Canyon", "Central Coast", "United States", "red", ["Syrah", "Grenache"], (3, 16)),
    ("Happy Canyon of Santa Barbara", "Central Coast", "United States", "red", ["Cabernet Sauvignon", "Sauvignon Blanc"], (4, 18)),
    ("Los Olivos District", "Central Coast", "United States", "red", ["Syrah", "Grenache"], (3, 15)),
    ("Arroyo Grande Valley", "Central Coast", "United States", "red", ["Pinot Noir", "Chardonnay"], (3, 15)),
    ("Adelaida District", "Central Coast", "United States", "red", ["Cabernet Sauvignon", "Syrah", "Zinfandel"], (4, 20)),
    ("Willow Creek District", "Central Coast", "United States", "red", ["Syrah", "Grenache", "Mourvedre"], (4, 18)),
    ("Templeton Gap District", "Central Coast", "United States", "red", ["Syrah", "Zinfandel"], (3, 16)),
    ("El Pomar District", "Central Coast", "United States", "red", ["Cabernet Sauvignon", "Syrah"], (3, 16)),
    ("Creston District", "Central Coast", "United States", "red", ["Cabernet Sauvignon", "Syrah"], (3, 16)),
    ("San Miguel District", "Central Coast", "United States", "red", ["Cabernet Sauvignon", "Petite Sirah"], (3, 16)),
    ("York Mountain", "Central Coast", "United States", "red", ["Pinot Noir", "Zinfandel"], (3, 16)),
    ("Santa Margarita Ranch", "Central Coast", "United States", "red", ["Cabernet Sauvignon", "Pinot Noir"], (3, 16)),
    # ---- Sierra Foothills & Central Valley ----
    ("Sierra Foothills", "Sierra Foothills", "United States", "red", ["Zinfandel", "Syrah"], (3, 15)),
    ("Amador County", "Sierra Foothills", "United States", "red", ["Zinfandel", "Barbera"], (3, 16)),
    ("Shenandoah Valley of California", "Sierra Foothills", "United States", "red", ["Zinfandel", "Barbera"], (3, 16)),
    ("El Dorado", "Sierra Foothills", "United States", "red", ["Zinfandel", "Syrah", "Barbera"], (3, 15)),
    ("Lodi", "Lodi", "United States", "red", ["Zinfandel", "Cabernet Sauvignon"], (2, 12)),
    ("Clarksburg", "Clarksburg", "United States", "white", ["Chenin Blanc", "Petite Sirah"], (2, 10)),
    ("Suisun Valley", "Suisun Valley", "United States", "red", ["Petite Sirah", "Cabernet Sauvignon"], (3, 14)),
    # ---- Umbrella appellations, so a broad answer still resolves ----
    ("California", "California", "United States", "red", ["Cabernet Sauvignon", "Chardonnay", "Zinfandel"], (2, 12)),
    ("North Coast", "North Coast", "United States", "red", ["Cabernet Sauvignon", "Zinfandel"], (3, 15)),
    ("Central Coast", "Central Coast", "United States", "red", ["Pinot Noir", "Chardonnay", "Syrah"], (2, 14)),
]
# fmt: on


# fmt: off
CALIFORNIA_PRODUCERS: list[tuple[str, str]] = [
    # ================= NAPA =================
    ("Arista Winery", "Russian River Valley"),
    ("Accendo Cellars", "Napa Valley"), ("Acumen", "Atlas Peak"),
    ("Amizetta", "Napa Valley"), ("Amuse Bouche", "Napa Valley"),
    ("Andrew Geoffrey", "Diamond Mountain District"), ("Anderson's Conn Valley", "Napa Valley"),
    ("Antica Napa Valley", "Atlas Peak"), ("Araujo Estate", "Calistoga"),
    ("Arkenstone", "Howell Mountain"), ("Arns Winery", "Spring Mountain District"),
    ("Ashes & Diamonds", "Oak Knoll District"), ("Atalon", "Napa Valley"),
    ("August Briggs", "Calistoga"), ("B Cellars", "Oakville"),
    ("Barbour Vineyards", "Napa Valley"), ("Beaucanon", "Napa Valley"),
    ("Bell Cellars", "Yountville"), ("Benessere", "St. Helena"),
    ("Bevan Cellars", "Napa Valley"), ("Black Stallion", "Oak Knoll District"),
    ("Blackbird Vineyards", "Oak Knoll District"), ("Blankiet Estate", "Yountville"),
    ("Boich Family Cellar", "Napa Valley"), ("Bond", "Napa Valley"),
    ("Brand Napa Valley", "Pritchard Hill"), ("Bremer Family", "Howell Mountain"),
    ("Brown Estate", "Chiles Valley"), ("Buccella", "Napa Valley"),
    ("Burgess Cellars", "Howell Mountain"), ("Cain Five", "Spring Mountain District"),
    ("Cardinale", "Oakville"), ("Carter Cellars", "Oakville"),
    ("Casa Piena", "Yountville"), ("Cathiard Vineyard", "Napa Valley"),
    ("Caymus-Suisun", "Suisun Valley"), ("Ceja Vineyards", "Carneros"),
    ("Chase Cellars", "St. Helena"), ("Checkerboard Vineyards", "Diamond Mountain District"),
    ("Chateau Boswell Winery", "St. Helena"), ("Chateau Potelle", "Mount Veeder"),
    ("Cimarossa", "Howell Mountain"), ("Clark-Claudon", "Napa Valley"),
    ("Cliff Lede Vineyards", "Stags Leap District"), ("Clos Pepe", "Sta. Rita Hills"),
    ("Constant", "Diamond Mountain District"), ("Corison Winery", "St. Helena"),
    ("Crocker & Starr", "St. Helena"), ("Cornerstone Cellars", "Napa Valley"),
    ("Dakota Shy", "Napa Valley"), ("Dana Estates", "Rutherford"),
    ("Darioush", "Napa Valley"), ("David Arthur", "Napa Valley"),
    ("Davis Estates", "Calistoga"), ("Detert Family", "Oakville"),
    ("Diamond Mountain Vineyard", "Diamond Mountain District"), ("DR Stephens", "St. Helena"),
    ("Duckhorn Decoy", "Napa Valley"), ("Dunn Howell Mountain", "Howell Mountain"),
    ("Eisele Vineyard", "Calistoga"), ("Elyse Winery", "Napa Valley"),
    ("Ehlers Estate", "St. Helena"), ("Envy Wines", "Calistoga"),
    ("Failla Napa", "Napa Valley"), ("Fairchild Napa Valley", "Napa Valley"),
    ("Fantesca", "Spring Mountain District"), ("Favia", "Coombsville"),
    ("Flora Springs Winery", "St. Helena"), ("Forman Vineyard", "St. Helena"),
    ("Freemark Abbey Winery", "St. Helena"), ("Gamble Family", "Oakville"),
    ("Gandona", "Pritchard Hill"), ("Gemstone Vineyard", "Yountville"),
    ("Ghost Block", "Oakville"), ("Grace Family Vineyards", "St. Helena"),
    ("Groth Vineyards", "Oakville"), ("Hartwell Estate", "Stags Leap District"),
    ("Heitz Wine Cellars", "St. Helena"), ("Hendry Ranch", "Napa Valley"),
    ("Hourglass", "Calistoga"), ("Hunnicutt", "St. Helena"),
    ("Hyde Vineyards", "Carneros"), ("Jarvis Estate", "Napa Valley"),
    ("Joseph Phelps Vineyards", "St. Helena"), ("Kelly Fleming", "Calistoga"),
    ("Keenan Winery", "Spring Mountain District"), ("Kenzo Estate", "Napa Valley"),
    ("Knights Bridge", "Knights Valley"), ("Kongsgaard", "Napa Valley"),
    ("Krupp Brothers", "Napa Valley"), ("La Jota", "Howell Mountain"),
    ("Lail Vineyards", "Napa Valley"), ("Lamborn Family", "Howell Mountain"),
    ("Lancaster Estate", "Alexander Valley"), ("Larkin Wines", "Napa Valley"),
    ("Levy & McClellan", "Napa Valley"), ("Lewis Cellars", "Napa Valley"),
    ("Lindstrom Wines", "Stags Leap District"), ("Long Meadow Ranch", "Napa Valley"),
    ("Louis M. Martini Winery", "Napa Valley"), ("Macauley", "Napa Valley"),
    ("MacDonald Vineyards", "Oakville"), ("Maroon Wines", "Napa Valley"),
    ("Mascot", "Napa Valley"), ("Materra", "Oak Knoll District"),
    ("Matthiasson", "Napa Valley"), ("Melka Wines", "St. Helena"),
    ("Memento Mori Winery", "Napa Valley"), ("Merryvale", "St. Helena"),
    ("Mi Sueno", "Napa Valley"), ("Mondavi Reserve", "Oakville"),
    ("Morlet Family", "St. Helena"), ("Mount Brave", "Mount Veeder"),
    ("Myriad Cellars", "Napa Valley"), ("Neal Family", "Howell Mountain"),
    ("Newton Vineyard", "Spring Mountain District"), ("Nine Suns", "Pritchard Hill"),
    ("Notre Vin", "Napa Valley"), ("Oakville Ranch", "Oakville"),
    ("Ovid Napa Valley", "Pritchard Hill"), ("Palmaz Vineyards", "Coombsville"),
    ("Paradigm", "Oakville"), ("Parallel", "Napa Valley"),
    ("Patland Estate", "Napa Valley"), ("Paul Hobbs Napa", "Napa Valley"),
    ("Pahlmeyer", "Napa Valley"), ("Peju Province", "Rutherford"),
    ("Perliss Estate", "Calistoga"), ("Philip Togni", "Spring Mountain District"),
    ("Piña Napa Valley", "Rutherford"), ("Plumpjack Winery", "Oakville"),
    ("Post & Beam", "St. Helena"), ("Pott Wine", "Napa Valley"),
    ("Pulido-Walker", "Mount Veeder"), ("Quixote", "Stags Leap District"),
    ("Ramey Napa", "Napa Valley"),
    ("Reverie", "Diamond Mountain District"), ("Revana Family", "St. Helena"),
    ("Rivers-Marie", "Sonoma Coast"), ("Robert Craig Winery", "Howell Mountain"),
    ("Robert Foley", "Napa Valley"), ("Rocca Family", "Yountville"),
    ("Rombauer", "Napa Valley"), ("Rudd Estate", "Oakville"),
    ("Salvestrin", "St. Helena"), ("Sandlands", "Napa Valley"),
    ("Schrader", "Oakville"), ("Seavey Vineyard", "Napa Valley"),
    ("Shafer", "Stags Leap District"), ("Sherwin Family", "Spring Mountain District"),
    ("Signorello Estate", "Napa Valley"), ("Silver Ghost", "Napa Valley"),
    ("Sinegal Estate", "St. Helena"), ("Sloan Estate", "Rutherford"),
    ("Smith Devereux", "Napa Valley"), ("Snowden Vineyards", "St. Helena"),
    ("Spring Mountain Vineyard", "Spring Mountain District"), ("Staglin Family", "Rutherford"),
    ("Stony Hill Vineyard", "Spring Mountain District"), ("Switchback Ridge", "Calistoga"),
    ("Tamber Bey Vineyards", "Calistoga"), ("Tor Kenward Family", "Napa Valley"),
    ("Trefethen Family", "Oak Knoll District"), ("Trespass", "Napa Valley"),
    ("Trinchero Napa Valley", "St. Helena"), ("Tuck Beckstoffer", "Napa Valley"),
    ("Twomey", "Calistoga"), ("V. Sattui", "St. Helena"),
    ("Venge Family Reserve", "Napa Valley"), ("Viader", "Howell Mountain"),
    ("Vice Versa", "Napa Valley"), ("Vineyard 29", "St. Helena"),
    ("Vine Cliff", "Oakville"), ("Volker Eisele", "Chiles Valley"),
    ("W.H. Smith", "Sonoma Coast"), ("Wheeler Farms", "St. Helena"),
    ("White Rock Vineyards", "Coombsville"), ("Whitehall Lane Winery", "Rutherford"),
    ("Yao Family Wines", "Napa Valley"), ("ZD", "Rutherford"),
    ("Zeitgeist Cellars", "Napa Valley"), ("Ziata", "Napa Valley"),

    # ================= SONOMA =================
    ("Arista", "Russian River Valley"), ("Aperture Cellars", "Alexander Valley"),
    ("Anaba Wines", "Carneros"), ("Alysian", "Russian River Valley"),
    ("Ampelos", "Sta. Rita Hills"), ("Auteur", "Sonoma Coast"),
    ("Banshee", "Sonoma County"), ("Bacigalupi", "Russian River Valley"),
    ("Bartlett Hall", "Sonoma County"), ("Battaglini", "Russian River Valley"),
    ("Bedrock Wine Co.", "Sonoma Valley"), ("Belden Barns", "Sonoma Mountain"),
    ("Benovia", "Russian River Valley"), ("Black Kite Cellars", "Anderson Valley"),
    ("Bucher Wines", "Russian River Valley"), ("Cakebread Sonoma", "Sonoma County"),
    ("Carlisle Winery", "Russian River Valley"), ("Chalk Hill Estate", "Chalk Hill"),
    ("Cline Cellars", "Carneros"), ("Cobb Wines", "Sonoma Coast"),
    ("Comstock Wines", "Dry Creek Valley"), ("Corner 103", "Sonoma Valley"),
    ("Davis Bynum", "Russian River Valley"), ("DeLoach Vineyards", "Russian River Valley"),
    ("Donelan Family", "Sonoma County"), ("Dry Creek Vineyards", "Dry Creek Valley"),
    ("Dutton Estate", "Green Valley of Russian River Valley"),
    ("Eco Terreno", "Alexander Valley"), ("Enriquez Estate", "Russian River Valley"),
    ("Ernest Vineyards", "Sonoma Coast"), ("Fisher Vineyards", "Fountaingrove District"),
    ("Flanagan", "Bennett Valley"), ("Flambeaux", "Dry Creek Valley"),
    ("Fort Ross Vineyard", "Fort Ross-Seaview"), ("Foppiano", "Russian River Valley"),
    ("Frick Winery", "Dry Creek Valley"), ("Gary Farrell Winery", "Russian River Valley"),
    ("Halleck Vineyard", "Russian River Valley"), ("Hamel Family", "Moon Mountain District"),
    ("Hartford Family", "Green Valley of Russian River Valley"),
    ("Hawkes", "Alexander Valley"), ("Hobo Wine Company", "Sonoma County"),
    ("Idlewild", "Mendocino Ridge"), ("Inman Family", "Russian River Valley"),
    ("Jaxon Keys", "Redwood Valley"), ("Joseph Jewell", "Russian River Valley"),
    ("Kamen Estate", "Moon Mountain District"), ("Keller Estate", "Petaluma Gap"),
    ("Kokomo Winery", "Dry Creek Valley"), ("Kutch Wines", "Sonoma Coast"),
    ("La Follette", "Russian River Valley"), ("Landmark Vineyards", "Sonoma Valley"),
    ("Lasseter Family", "Sonoma Valley"), ("Ledson", "Sonoma Valley"),
    ("Limerick Lane", "Russian River Valley"), ("Lioco", "Sonoma County"),
    ("Loxton Cellars", "Sonoma Valley"), ("MacPhail", "Sonoma Coast"),
    ("Mauritson Wines", "Rockpile"), ("Martinelli", "Russian River Valley"),
    ("Medlock Ames", "Alexander Valley"), ("Migration Sonoma", "Russian River Valley"),
    ("Moshin Vineyards", "Russian River Valley"), ("Mount Eden Sonoma", "Sonoma County"),
    ("Nalle Winery", "Dry Creek Valley"), ("Notre Vue Estate", "Chalk Hill"),
    ("Paul Mathew", "Russian River Valley"), ("Pax Mahle", "Sonoma Coast"),
    ("Pellegrini Family", "Russian River Valley"), ("Pey-Marin", "Petaluma Gap"),
    ("Porter Creek", "Russian River Valley"), ("Preston Farm & Winery", "Dry Creek Valley"),
    ("Ramey Sonoma", "Russian River Valley"), ("Ravenswood Zinfandel", "Sonoma County"),
    ("Ridge Geyserville", "Alexander Valley"), ("Robert Young", "Alexander Valley"),
    ("Roessler Cellars", "Sonoma Coast"), ("Rued Winery", "Dry Creek Valley"),
    ("Sbragia Family", "Dry Creek Valley"), ("Scherrer Winery", "Alexander Valley"),
    ("Sebastiani", "Sonoma Valley"), ("Senses Wines", "Sonoma Coast"),
    ("Sextant Sonoma", "Sonoma County"), ("Small Vines", "Green Valley of Russian River Valley"),
    ("Sonoma Loeb", "Sonoma County"), ("St. Anne's Crossing", "Sonoma Valley"),
    ("Stephen Ross", "Edna Valley"), ("Stuhlmuller", "Alexander Valley"),
    ("Sunce Winery", "Russian River Valley"), ("Talisman Wines", "Sonoma County"),
    ("Thomas George Estates", "Russian River Valley"), ("Timber Crest", "Dry Creek Valley"),
    ("Trione", "Alexander Valley"), ("Twomey Sonoma", "Russian River Valley"),
    ("Two Shepherds", "Russian River Valley"), ("Unti Vineyards", "Dry Creek Valley"),
    ("Verite", "Sonoma County"), ("Walt Wines", "Sonoma Coast"),
    ("Wattle Creek", "Alexander Valley"), ("Wilson Winery", "Dry Creek Valley"),
    ("Zialena", "Alexander Valley"), ("Ziegler Family", "Sonoma County"),

    # ================= MENDOCINO / LAKE =================
    ("Bonterra", "Mendocino Ridge"), ("Fetzer", "Redwood Valley"),
    ("Husch Vineyards", "Anderson Valley"), ("Lula Cellars", "Anderson Valley"),
    ("Maggy Hawk", "Anderson Valley"), ("Phillips Hill", "Anderson Valley"),
    ("Toulouse Vineyards", "Anderson Valley"), ("Pennyroyal Farm", "Anderson Valley"),
    ("Baxter Winery", "Mendocino Ridge"), ("Brutocao", "Redwood Valley"),
    ("Parducci", "Redwood Valley"), ("Obsidian Ridge", "Red Hills Lake County"),
    ("Steele Wines", "Lake County"), ("Gregory Graham", "Red Hills Lake County"),
    ("Shannon Ridge", "Lake County"), ("Langtry Estate", "Guenoc Valley"),

    # ================= MONTEREY / SAN BENITO / BAY =================
    ("Calera", "Mount Harlan"), ("Chalone Vineyard", "Chalone"),
    ("Bernardus", "Carmel Valley"), ("Talbott Vineyards", "Santa Lucia Highlands"),
    ("Roar Wines", "Santa Lucia Highlands"), ("ROAR", "Santa Lucia Highlands"),
    ("Wrath Wines", "Santa Lucia Highlands"), ("Paraiso Vineyards", "Santa Lucia Highlands"),
    ("McIntyre Vineyards", "Santa Lucia Highlands"), ("Mer Soleil", "Santa Lucia Highlands"),
    ("Caraccioli Cellars", "Santa Lucia Highlands"), ("Pelerin", "Santa Lucia Highlands"),
    ("Jackson Estate Monterey", "Monterey"), ("Scheid Vineyards", "Monterey"),
    ("Hahn Family", "Santa Lucia Highlands"), ("J. Lohr", "Paso Robles"),
    ("Wente Vineyards", "Livermore Valley"), ("Concannon", "Livermore Valley"),
    ("Steven Kent", "Livermore Valley"), ("Murrieta's Well", "Livermore Valley"),
    ("Ridge Cordon", "Santa Clara Valley"), ("Clos LaChance", "Santa Clara Valley"),
    ("Cinnabar", "Santa Cruz Mountains"), ("Big Basin Vineyards", "Santa Cruz Mountains"),
    ("Ridge Jimsomare", "Santa Cruz Mountains"), ("Varner", "Santa Cruz Mountains"),
    ("Neely", "Santa Cruz Mountains"), ("Beauregard Vineyards", "Santa Cruz Mountains"),
    ("Storrs", "Santa Cruz Mountains"), ("Burrell School", "Santa Cruz Mountains"),
    ("Bonny Doon Vineyard", "Santa Cruz Mountains"), ("Madson Wines", "Santa Cruz Mountains"),
    ("Cleavage Creek", "Contra Costa County"), ("Bedrock Heritage", "Contra Costa County"),

    # ================= PASO ROBLES & SLO =================
    ("Denner Vineyards", "Willow Creek District"), ("Linne Calodo", "Willow Creek District"),
    ("Turley Paso Robles", "Paso Robles"), ("Villa Creek", "Willow Creek District"),
    ("Torrin", "Willow Creek District"), ("Jada Vineyard", "Willow Creek District"),
    ("Law Estate", "Adelaida District"), ("Tablas Creek Vineyard", "Adelaida District"),
    ("Halter Ranch Vineyard", "Adelaida District"), ("Justin Winery", "Adelaida District"),
    ("Daou Vineyards", "Adelaida District"), ("Adelaida Cellars", "Adelaida District"),
    ("Epoch Estate Wines", "Willow Creek District"), ("Saxum Vineyards", "Willow Creek District"),
    ("Booker Vineyard", "Willow Creek District"), ("Alta Colina", "Adelaida District"),
    ("Caliza Winery", "Willow Creek District"), ("Copia Vineyards", "Paso Robles"),
    ("Austin Hope", "Paso Robles"), ("Hope Family Wines", "Paso Robles"),
    ("Treana", "Paso Robles"), ("Liberty School", "Paso Robles"),
    ("Ancient Peaks", "Santa Margarita Ranch"), ("Niner Wine Estates", "Willow Creek District"),
    ("Robert Hall", "El Pomar District"), ("Eberle Winery", "Paso Robles"),
    ("Peachy Canyon", "Paso Robles"), ("Opolo Vineyards", "Willow Creek District"),
    ("Tobin James", "Paso Robles"), ("Vina Robles", "Paso Robles"),
    ("Broken Earth", "Paso Robles"), ("Calcareous Vineyard", "Adelaida District"),
    ("Cass Winery", "Creston District"), ("Chronic Cellars", "Paso Robles"),
    ("Clesi Wines", "Paso Robles"), ("Croad Vineyards", "Paso Robles"),
    ("Derby Wine Estates", "Templeton Gap District"), ("Dilecta", "Paso Robles"),
    ("Eos Estate", "Paso Robles"), ("Four Vines", "Paso Robles"),
    ("Grey Wolf", "Paso Robles"), ("Hearst Ranch Winery", "Paso Robles"),
    ("Herman Story", "Paso Robles"), ("JUSTIN Isosceles", "Adelaida District"),
    ("Kukkula", "Adelaida District"), ("L'Aventure Winery", "Willow Creek District"),
    ("Lone Madrone", "Adelaida District"), ("McPrice Myers", "Paso Robles"),
    ("Nine Stones", "Paso Robles"), ("Ortman Family", "Edna Valley"),
    ("Paix Sur Terre", "Paso Robles"), ("Pomar Junction", "El Pomar District"),
    ("Ranchero Cellars", "Paso Robles"), ("Rangeland", "Adelaida District"),
    ("Ravenswood Paso", "Paso Robles"), ("Red Soles", "Paso Robles"),
    ("Rotta Winery", "Templeton Gap District"), ("San Antonio Winery", "Paso Robles"),
    ("Sculpterra", "Paso Robles"), ("Sextant Wines", "Paso Robles"),
    ("Still Waters", "Paso Robles"), ("Summerwood", "Willow Creek District"),
    ("Tannat Estate", "Paso Robles"), ("Terry Hoage", "Willow Creek District"),
    ("Thacher Winery", "Adelaida District"), ("Turtle Rock", "Adelaida District"),
    ("Vines on the Marycrest", "Paso Robles"), ("Whalebone Vineyard", "Adelaida District"),
    ("Zenaida Cellars", "Adelaida District"), ("Claiborne & Churchill", "Edna Valley"),
    ("Baileyana", "Edna Valley"), ("Tolosa Winery", "Edna Valley"),
    ("Wolff Vineyards", "Edna Valley"), ("Laetitia Vineyard", "Arroyo Grande Valley"),
    ("Talley Vineyards Arroyo Grande", "Arroyo Grande Valley"),
    ("Saucelito Canyon", "Arroyo Grande Valley"), ("Kynsi", "Edna Valley"),

    # ================= SANTA BARBARA =================
    ("Sea Smoke Cellars", "Sta. Rita Hills"), ("Peake Ranch", "Sta. Rita Hills"),
    ("Dragonette Cellars", "Sta. Rita Hills"), ("Alma Rosa", "Sta. Rita Hills"),
    ("Babcock", "Sta. Rita Hills"), ("Lafond", "Sta. Rita Hills"),
    ("Foley Estates", "Sta. Rita Hills"), ("Ken Brown Wines", "Sta. Rita Hills"),
    ("Longoria", "Sta. Rita Hills"), ("Pali Wine Co.", "Sta. Rita Hills"),
    ("Siduri Santa Barbara", "Sta. Rita Hills"), ("Tyler Winery", "Sta. Rita Hills"),
    ("The Hilt", "Sta. Rita Hills"), ("Chanin Wine", "Sta. Rita Hills"),
    ("Presqu'ile", "Santa Maria Valley"), ("Cambria Estate", "Santa Maria Valley"),
    ("Byron", "Santa Maria Valley"), ("Rancho Sisquoc", "Santa Maria Valley"),
    ("Riverbench", "Santa Maria Valley"), ("Kenneth Volk", "Santa Maria Valley"),
    ("Cottonwood Canyon", "Santa Maria Valley"), ("Costa de Oro", "Santa Maria Valley"),
    ("Stolpman Vineyards", "Ballard Canyon"), ("Beckmen Vineyards", "Ballard Canyon"),
    ("Rusack", "Ballard Canyon"), ("Jonata", "Ballard Canyon"),
    ("Larner Vineyard", "Ballard Canyon"), ("Star Lane Vineyard", "Happy Canyon of Santa Barbara"),
    ("Grimm's Bluff", "Happy Canyon of Santa Barbara"), ("Crown Point", "Happy Canyon of Santa Barbara"),
    ("Andrew Murray", "Los Olivos District"), ("Brander Vineyard", "Los Olivos District"),
    ("Buttonwood Farm", "Los Olivos District"), ("Curtis Winery", "Los Olivos District"),
    ("Refugio Ranch", "Los Olivos District"), ("Roblar", "Los Olivos District"),
    ("Sunstone", "Santa Barbara County"), ("Gainey Vineyard", "Santa Barbara County"),
    ("Firestone Vineyard", "Santa Barbara County"), ("Qupe", "Santa Barbara County"),
    ("Ojai Vineyard", "Santa Barbara County"), ("Margerum", "Santa Barbara County"),
    ("Jaffurs", "Santa Barbara County"), ("Zotovich", "Sta. Rita Hills"),
    ("Kessler-Haak", "Sta. Rita Hills"), ("Storm Wines", "Sta. Rita Hills"),
    ("Racines", "Sta. Rita Hills"), ("Liquid Farm Wines", "Sta. Rita Hills"),

    # ================= SIERRA FOOTHILLS, LODI & VALLEY =================
    ("Turley Amador", "Amador County"), ("Terre Rouge", "Shenandoah Valley of California"),
    ("Easton Wines", "Shenandoah Valley of California"), ("Renwood", "Amador County"),
    ("Sobon Estate", "Shenandoah Valley of California"), ("Shenandoah Vineyards", "Shenandoah Valley of California"),
    ("Vino Noceto", "Shenandoah Valley of California"), ("Andis Wines", "Amador County"),
    ("Scott Harvey", "Amador County"), ("Boeger Winery", "El Dorado"),
    ("Holly's Hill", "El Dorado"), ("Skinner Vineyards", "El Dorado"),
    ("Lava Cap", "El Dorado"), ("Miraflores", "El Dorado"),
    ("Michael David Winery", "Lodi"), ("Klinker Brick", "Lodi"),
    ("Bokisch Vineyards", "Lodi"), ("Harney Lane", "Lodi"),
    ("McCay Cellars", "Lodi"), ("Turley Lodi", "Lodi"),
    ("Oak Ridge Winery", "Lodi"), ("Peirano Estate", "Lodi"),
    ("St. Amant", "Lodi"), ("Ironstone Vineyards", "Sierra Foothills"),
    ("Bogle Vineyards", "Clarksburg"), ("Wilson Vineyards", "Clarksburg"),
    ("Ledgewood Creek", "Suisun Valley"),

    # ================= CALIFORNIA-WIDE / VALUE LABELS =================
    ("Ridge California", "California"),
    ("Frog's Leap Winery", "Rutherford"), ("Cline Family", "California"),
    ("Sean Minor", "California"), ("Hess Select", "California"),
    ("Josh Cellars", "California"), ("Meiomi", "California"),
    ("Belle Glos", "Santa Maria Valley"), ("Elouan", "California"),
    ("Bread & Butter", "California"), ("Decoy", "California"),
    ("Educated Guess", "Napa Valley"), ("Ghost Pines", "California"),
    ("Apothic", "California"), ("Bogle", "Clarksburg"),
    ("Cameron Hughes", "California"), ("Charles Krug Winery", "St. Helena"),
    ("Trinitas", "Carneros"), ("Angels Ink", "California"),
    ("Massican", "Napa Valley"), ("Matthiasson Wines", "Napa Valley"),
    ("Hoopes Vineyard", "Oakville"), ("Ancien Wines", "Carneros"),
    ("Somnium", "Napa Valley"), ("Failla Wines", "Sonoma Coast"),
    ("Ceritas Wines", "Sonoma Coast"),
]
# fmt: on
