// "You may also like", reasoned over the whole cellar rather than one bottle.

import { api } from '../api.js';
import { state } from '../state.js';
import { el, empty, field, loading, money, mount, plural, toast } from '../ui.js';

export async function discoverView() {
  const cellars = await state.cellars();
  const active = state.activeCellar(cellars);

  const priceInput = el('input', { type: 'number', min: '0', placeholder: 'No limit' });
  const noteInput = el('input', { placeholder: 'e.g. for a steak dinner, or something to age 20 years' });
  const scopeInput = el('select', {},
    el('option', { value: '' }, 'All cellars'),
    ...cellars.map((c) => el('option', { value: c.id, selected: c.id === active?.id }, c.name)));

  const results = el('div', {});

  const run = async () => {
    results.replaceChildren(el('div', { class: 'card' }, loading('Reading your cellar and thinking…')));
    try {
      const data = await api.recommendations({
        cellar_id: scopeInput.value ? Number(scopeInput.value) : null,
        price_ceiling: priceInput.value ? Number(priceInput.value) : null,
        note: noteInput.value.trim() || null,
        count: 8,
      });
      results.replaceChildren(...renderSuggestions(data));
    } catch (error) {
      results.replaceChildren(el('div', { class: 'banner error' }, error.message));
    }
  };

  const form = el('form', { onSubmit: (event) => { event.preventDefault(); run(); } },
    el('div', { class: 'field-grid' },
      field('Based on', scopeInput),
      field('Max price per bottle', priceInput),
      field('Anything specific?', noteInput)),
    el('div', { class: 'btn-row' },
      el('button', { class: 'btn-primary', type: 'submit' }, '✨ Suggest wines')));

  mount(
    el('div', { class: 'page-head' },
      el('div', {}, el('h1', {}, 'Discover'),
        el('p', {}, 'Suggestions built from what you actually own and how you rated it.'))),
    el('section', { class: 'card' }, form),
    results);

  if (!cellars.length) {
    results.replaceChildren(empty('🗄️', 'Nothing to reason from yet',
      el('p', {}, 'Add a few bottles first — the suggestions are drawn from your own cellar.')));
    return;
  }
  run();
}

function renderSuggestions(data) {
  const suggestions = data.suggestions || [];
  if (!suggestions.length) {
    return [el('div', { class: 'banner' }, 'No suggestions came back. Try again, or widen the price limit.')];
  }

  const basis = data.based_on
    ? el('p', { class: 'hint' },
        `From ${plural(data.based_on.bottle_lots, 'lot')}`
        + (data.based_on.top_varietals?.length ? ` · leaning ${data.based_on.top_varietals.slice(0, 3).join(', ')}` : '')
        + (data.based_on.taste_profile_entries ? ` · ${plural(data.based_on.taste_profile_entries, 'taste-profile entry', 'taste-profile entries')}` : ''))
    : null;

  return [
    el('div', { style: 'margin:.8rem 0 .5rem' }, el('h2', {}, 'Suggested next'), basis),
    el('div', { class: 'suggest' }, ...suggestions.map((suggestion) => el('div', {
      class: 'suggest-item' + (suggestion.already_owned ? ' owned' : ''),
    },
      el('div', { class: 'title' },
        [suggestion.producer, suggestion.wine_name].filter(Boolean).join(' '),
        suggestion.already_owned ? el('span', { class: 'tag', style: 'margin-left:.5rem' }, 'already yours') : null),
      el('div', { class: 'meta hint' },
        [(suggestion.varietals || []).join(', '), suggestion.region, suggestion.country].filter(Boolean).join(' · ')
        + (suggestion.typical_price_usd ? ` · ~${money(suggestion.typical_price_usd)}` : '')),
      suggestion.because ? el('div', { class: 'because' }, suggestion.because) : null,
      el('div', { class: 'btn-row', style: 'margin-top:.5rem' },
        el('a', {
          class: 'btn btn-sm btn-ghost',
          href: '#/scan?manual=1',
          onClick: () => toast('Fill in the details to add it to a cellar'),
        }, '+ Add to cellar'))))),
    el('p', { class: 'hint', style: 'margin-top:.8rem' },
      'Suggestions are generated by a language model from your cellar contents — a starting point for a shopping list, not a merchant listing.'),
  ];
}
